apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
  name: ftps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps_image
        imagePullPolicy: Never
        name: ftps
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  ports:
  - name: command-ctrl
    port: 20
    targetPort: 20
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftps-pasv
    port: 30000
    protocol: TCP
    targetPort: 30000
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104